### PR TITLE
Include deep linkage as a principle.

### PR DESCRIPTION
**Pull request by deanmarano**
Hi there! I think this is an awesome idea, and I'll definitely be sharing this around. One thing that for me is very important when building apps is the ability to share a URL - either with myself or with others - easily. By leveraging this built in feature of the web, it makes it much easier to share, bookmark, and be a good web citizen.

Organizationally I don't know if this makes sense in the `Web applications should work everywhere` section, but just wanted to start a conversation if you're open to it.

Thanks for making this! It's much appreciated.

Dean

### CODE REVIEW

**Comment by ascott1** [comment]
Oh, I _really_ like that @deanmarano. It reminds me of a point from [this talk by Matt Haughey](http://a.wholelottanothing.org/2012/03/my-webstock-talk.html) from a few years ago, suggesting to use "Permanent, human-readable clean URLs."

**Comment by ascott1** [comment]
In fact, what do you think of using that language in addition to the deep links?

**Comment by deanmarano** [comment]
That's an awesome resource! After reading, I've changed the wording around a bit to include human language as well as permanence (which was something I didn't originally think of, but is equally as important).

**Comment by ascott1** [comment]
:boom: Glad you liked that talk! Merging and will push to production. Thanks for contributing @deanmarano! I'll be adding a `humans.txt` file shortly with a list of contributors, reviewers, etc which will also be referenced in book. Are you ok with being included?

**Comment by deanmarano** [comment]
Yup! Thanks so much.

**Pull request merged**
